### PR TITLE
Ghidra 11.0+ Fix

### LINKED ISSUE #16: Not working since Ghidra 11.0
After rebuilding the extension for Ghidra 11.1, loading an RPL (in this case, `camera.rpl`) results in this exception
```
Cannot invoke "ghidra.program.model.listing.Data.getLength()" because "d" is null
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.listing.Data.getLength()" because "d" is null
	at cafeloader.Cafe_ElfExtension.processRplFileInfo(Cafe_ElfExtension.java:314)
	at cafeloader.Cafe_ElfExtension.processElf(Cafe_ElfExtension.java:137)
	at ghidra.app.util.opinion.ElfProgramBuilder.load(ElfProgramBuilder.java:170)
	at ghidra.app.util.opinion.ElfProgramBuilder.loadElf(ElfProgramBuilder.java:111)
	at ghidra.app.util.opinion.CafeLoader.load(CafeLoader.java:76)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:864)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:395)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:338)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

---------------------------------------------------
Build Date: 2024-Jun-07 1416 EDT
Ghidra Version: 11.1
Java Home: /usr/lib/jvm/java-21-openjdk-amd64
JVM Version: Private Build 21.0.2
OS: Linux 6.8.3-pikaos amd64
```
The same error shows for Ghidra 11.0 too

### PR DESCRIPTION
**Pull request by SuperDude88**
Fixes #16

### CODE REVIEW

File: src/main/java/cafeloader/Cafe_ElfExtension.java [hunk 1]
```diff
@@ -311,11 +311,10 @@ private void processRplFileInfo(ElfLoadHelper elfLoadHelper, ElfSectionHeader se
 				Address tagAddress = fileInfoAddr.add(tagOffset);
 				while (true) {
 					Data d = elfLoadHelper.createData(tagAddress, TerminatedStringDataType.dataType);
-					int length = d.getLength();
-					if (length == 0) {
+					if (d == null || d.getLength() <= 1) { // empty string has a length of 1 (just a null terminator)
```
Comment (aboood40091) [inline src/main/java/cafeloader/Cafe_ElfExtension.java]: I think a better fix would be to check "`if d is null or d.getLength() == 0 or d[0] == 0`." (I don't know the syntax for it in Java.)
